// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfO9f5VPkNVF00Txyep_XPMOtdtxtGOq0',
    appId: '1:358172667152:web:5b06592313bd992fa88995',
    messagingSenderId: '358172667152',
    projectId: 'hacakthon-rafay-123',
    authDomain: 'hacakthon-rafay-123.firebaseapp.com',
    storageBucket: 'hacakthon-rafay-123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUQffP9jq3ywXlxMz4VgTtweHlpOVJdwE',
    appId: '1:358172667152:android:d7184a729e400ad3a88995',
    messagingSenderId: '358172667152',
    projectId: 'hacakthon-rafay-123',
    storageBucket: 'hacakthon-rafay-123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDerdRULojl8kyUVB38tqe2Izasybd0QdE',
    appId: '1:358172667152:ios:db7ccba845399ba8a88995',
    messagingSenderId: '358172667152',
    projectId: 'hacakthon-rafay-123',
    storageBucket: 'hacakthon-rafay-123.appspot.com',
    iosClientId: '358172667152-qiqcikvfktcuo184nn8v2tdvj0daqs3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDerdRULojl8kyUVB38tqe2Izasybd0QdE',
    appId: '1:358172667152:ios:db7ccba845399ba8a88995',
    messagingSenderId: '358172667152',
    projectId: 'hacakthon-rafay-123',
    storageBucket: 'hacakthon-rafay-123.appspot.com',
    iosClientId: '358172667152-qiqcikvfktcuo184nn8v2tdvj0daqs3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
